# Landing pages for the Dual-qualify ads, on Ruchika's 21-step order.
# Reuses the page engine from ../NCA_SQEinspired_31Oct-2Nov/build_lps.py (CSS, facts box, cost table,
# details, end-only disclaimer). Run: python3 build_lps.py
import os, sys, importlib.util

HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("eng", os.path.join(HERE, "..", "NCA_SQEinspired_31Oct-2Nov", "build_lps.py"))
eng = importlib.util.module_from_spec(spec); spec.loader.exec_module(eng)
OUT = os.path.join(HERE, "landing_pages")
CTA_AD = "Try the route for Rs 10"  # the ad's button, repeated on the page (Rule 3)

PAGES = [
dict(stem="nca_d_01_two_licences_5plus", slug="nca-oct-d01-dual-experienced", ac="#1F3B5C", soft="#E9EEF5",
     title="Dual-qualify: India and Canada",
     qual="ADVOCATES · LITIGATORS · IN-HOUSE COUNSEL · 5+ YEARS OF PRACTICE",
     h1="Practising law for 5+ years? <em>Dual-qualify: India and Canada.</em>",
     offer="Keep your Indian licence and add Canada's. In 3 live days, we show you how to clear the NCA exams from India while your practice keeps running, and what the bar licensing step asks of you.",
     t={2:"You have one licence, and every year it is worth more",
        3:"What you want: a second licence, not a second career",
        4:"Failed alternative 1: treating Canada as a fresh start",
        5:"Failed alternative 2: waiting for a sabbatical that never comes",
        6:"Failed alternative 3: sending clients abroad to someone else",
        7:"The problem is not your seniority. It is a one-country position",
        8:"What one licence costs a senior lawyer",
        9:"The offer: try the dual-qualify route for Rs 10",
        10:"How a second licence is added, in 3 steps",
        11:"What you take away first: your two-licence map",
        12:"What a practice with two licences looks like",
        13:"Proof: in-house in Mumbai, then Vancouver",
        14:"Proof: one practice in Ludhiana, clients in three countries",
        15:"The work you do in the 3 days",
        16:"The details",
        17:"What each way of getting a Canadian licence costs",
        18:"The risk",
        19:"How to say it at the office",
        20:"Your next step",
        21:"Senior advocates already hold the first licence. This adds the second"},
     s={1:"This page is for advocates, litigators and in-house counsel with five or more years of practice, who want a Canadian licence beside the Indian one they already hold.",
        2:"<p>Five years in, your Indian licence carries real weight. Clients trust it, courts know your name, and juniors learn from you. But it is still a licence for one country.</p><p>When a client expands to Canada, or a family member asks about moving, the advice you can give stops at the border.</p>",
        3:"<p>You do not want to start over in Canada. You want to dual-qualify: to hold your Indian licence and a Canadian one, so the same experience works in two markets.</p>",
        4:"<p>The common picture of Canada is a lawyer who sells up, moves and starts again. For a senior advocate, that throws away the most valuable thing you own: a running practice and a name.</p><p>Dual qualification is the opposite. You add, you do not replace.</p>",
        5:"<p>Many experienced lawyers plan to look at Canada during a quiet year. A busy practice never offers one. The NCA exams are online and monthly, so they do not need a sabbatical. They need a plan that fits around the practice.</p>",
        6:"<p>When a client needs Canadian advice today, you refer them to someone else and the relationship moves with the matter. A second licence keeps that work, and that client, with you.</p>",
        7:"<p>Seniority is not the barrier. Your skills are proven. The barrier is that your licence positions you in one country.</p><p>The NCA's Certificate of Qualification, and then a provincial licence, repositions the same experience as recognised in Canada too. It is an addition to who you are, not a change.</p>",
        8:"<p>One licence quietly limits what your experience can earn and who can instruct you. Each year you stay single-licensed, the gap between what you know and where you may use it grows a little wider.</p><p>The NCA gives you five years to finish once you are assessed. Starting is the only part that cannot wait.</p>",
        9:"<p>Before you commit to anything, try the route. Our 3-day live bootcamp walks you through dual qualification from the first NCA application to bar licensing, for Rs 10, refundable.</p>"
          + eng.why("Why a Canadian licence is worth adding:"),
        10:"<ol class='steps'><li><b>NCA exams, from India.</b> The NCA assesses your LLB and assigns core subjects such as Canadian constitutional, administrative and criminal law, and professional responsibility. You write them online while you keep practising.</li><li><b>Canadian work from India, alongside.</b> Contracts valid in Canada, privacy policies for Canadian startups, research support for Canadian lawyers. It gives your second licence a track record.</li><li><b>Bar licensing.</b> With the Certificate of Qualification you take your province's licensing step, such as Ontario's licensing exams plus articling or the Law Practice Program. Then you hold two licences.</li></ol>",
        11:"<p>You leave Day 2 with a two-licence map. It shows what your Indian licence already covers and what the NCA will likely ask you to add. It also sets the order in which you add it around your existing matters.</p>",
        12:"<p>Indian clients keep coming to you for Indian work. New clients come for the Canadian side: Indian companies entering Canada, Canadian businesses with Indian links, families with matters in both countries.</p><div class='box'><p><b>Market data, not a promise:</b> Canada's Job Bank reports a median wage of CAD 65.21 an hour for lawyers in Ontario, with a moderate outlook for 2025 to 2027.</p><p class='src'>Source: jobbank.gc.ca, NOC 41101, Ontario.</p></div>",
        13:"<p>Hezal Shah was an in-house lawyer in Mumbai. In our bootcamp's own account, Hezal qualified first and then moved to Vancouver, rather than moving and hoping to qualify.</p>",
        14:"<p>Shashwat Jindal practises from Ludhiana. As our bootcamp tells it, the practice took on work for four US firms, a Canadian firm and five startups without leaving the city.</p><p>Two markets, one office.</p>",
        15:"<ul class='del'><li>Day 1: NCA question types, and an IRAC answer you write live</li><li>Day 2: your 12-month plan and two-licence map; finding Canadian work on Upwork and LinkedIn; a Canadian employment agreement</li><li>Day 3: a non-compete reviewed under Canadian law, incorporating a Canadian company, and the top 20 questions a CEO asks before expanding into Canada</li></ul>",
        16:eng.IMPL,
        17:eng.COST_TABLE,
        18:"<p>Rs 10, including GST. Refundable anytime, without a reason. Three sessions on a weekend and one evening, so no client meeting has to move.</p>",
        19:"<p class='quote'>\"I am adding a Canadian licence to my Indian one. The practice stays.\"</p><p>You are in the right room if you have practised for five years or more and want two licences, not a new start.</p>",
        20:"<p>Press the button, pay Rs 10, and the joining details come on WhatsApp and email. Block Saturday and Sunday, 2 to 5 PM, and Monday, 7 to 10 PM.</p>",
        21:"<p>Experienced advocates already hold the licence that took the longest to earn. The bootcamp shows you how to add Canada's beside it, one step at a time.</p>"}),

dict(stem="nca_d_02_myth_fact_canada", slug="nca-oct-d02-myth-fact", ac="#1E6A48", soft="#E6F1EA",
     title="Dual-qualify with the LLB you already have",
     qual="LLB HOLDERS · ADVOCATES · ASSOCIATES · IN-HOUSE · ANY PRACTICE AREA",
     h1="Want to practise law in Canada? <em>Dual-qualify with the LLB you already have.</em>",
     offer="Myth: you need a Canadian law degree first. Fact: the NCA assesses your Indian LLB and sets the exams. In 3 live days, we show you the route that follows, step by step.",
     t={2:"Everything you have heard about Canada starts with 'you would need'",
        3:"What you want: the facts, current to 2026",
        4:"Myth 1: you need a Canadian law degree first",
        5:"Myth 2: you have to move before you can start",
        6:"Myth 3: an English-medium LLB means no English test",
        7:"The real gap is not your degree. It is your position",
        8:"What believing the myths costs",
        9:"The offer: the facts, and the route, for Rs 10",
        10:"The route, in 3 steps",
        11:"What you take away first: your own fact sheet",
        12:"What changes when you act on facts",
        13:"Proof: the NCA exams, then the Ontario courts",
        14:"Proof: a litigator who moved with a job in hand",
        15:"The work you see in the 3 days",
        16:"The details",
        17:"The cost of each way in, in fact",
        18:"The risk",
        19:"The fact you can repeat at home",
        20:"Your next step",
        21:"If you want to practise law in Canada, start from the facts"},
     s={1:"This page is for anyone with an Indian LLB who wants to practise law in Canada and keeps hearing reasons it cannot be done.",
        2:"<p>You would need a Canadian degree. You would need to move first. You would need to be younger, or richer, or from a different university. Every conversation about Canada seems to start with what you lack.</p><p>Most of it is out of date, and some of it was never true.</p>",
        3:"<p>You want facts that apply to your degree in 2026, and a clear route you can act on.</p><p>That means three answers. Can my degree apply? What changed this year? And what exactly happens between applying and practising?</p>",
        4:"<p><b>The fact:</b> for an Indian LLB from a recognised university, the NCA usually assesses the degree you already hold and assigns exams. You do not need a Canadian degree to apply.</p><p>Many lawyers spend years and lakhs on a degree they did not need.</p><p>A Canadian degree remains a valid route for some people. For most Indian LLB holders, it is simply a longer and costlier one than they need.</p>",
        5:"<p><b>The fact:</b> the NCA exams are online and proctored, so you write them from India. Only the later bar licensing step brings you to Canada, and by then you know exactly what you are moving for.</p>",
        6:"<p><b>The fact, since 1 March 2026:</b> every NCA applicant now takes an English screening, whatever language the degree was taught in. Every applicant also completes a short Indigenous law course. Advice older than this year misses both.</p><p>Neither is a reason to stop. Both are short, defined steps, and once you know about them you can plan for them from the first week.</p>",
        7:"<p>Your degree is already common-law training. The real gap is position: today your LLB is recognised in India only. The NCA process positions the same degree as recognised in Canada. Facts close that gap; myths keep it open.</p>",
        8:"<p>Believing the myths has a price. Some lawyers pay for a degree they did not need. Others never start. Many wait for a moment that already came.</p><p>There is also a quieter cost. A lawyer who believes the route is closed stops reading about it, and so never learns when the facts change in their favour.</p>",
        9:"<p>A 3-day live bootcamp that replaces every myth with a sourced fact, then walks you along the route. Rs 10, refundable.</p>"
          + eng.why("Facts about Canada worth knowing:"),
        10:"<ol class='steps'><li><b>Apply to the NCA and clear its exams.</b> Your degree is assessed and your subjects are set. Add the 2026 English screening and Indigenous law course. Write the exams from India.</li><li><b>Get the Certificate of Qualification.</b> It puts you level with a Canadian common-law graduate for licensing.</li><li><b>Pass the bar licensing, then practise.</b> Each province runs its own. Ontario's is the licensing exams plus articling or the Law Practice Program. Ontario is reviewing its exams, so we teach what is current.</li></ol>",
        11:"<p>You leave with a one-page fact sheet for your own profile: your degree type, the English test you need, the subjects you are likely to be assigned, and the province that fits your plan.</p>",
        12:"<p>When you act on facts, the timeline becomes real. NCA exams run every month. The NCA puts the best case at about 10 months and the average at about two years, with five years to finish.</p><p>You stop asking whether Canada is possible and start asking which month to sit your next exam. That shift, from possibility to schedule, is what most people never make.</p>",
        13:"<p>Navkaran Singh, an Indian law graduate, cleared the NCA exams and went on to work in the Ontario courts, as our bootcamp tells it. Same degree type, same route.</p>",
        14:"<p>Yashika Malhotra was a litigator in India. In our bootcamp's own account, Yashika moved to Canada with a Canadian job already in hand, not the other way round.</p>",
        15:"<ul class='del'><li>Day 1: how the NCA assesses an Indian LLB, the question types, and an IRAC answer you write</li><li>Day 2: the 2026 English screening and Indigenous law course, your 12-month plan, and finding Canadian work from India</li><li>Day 3: bar licensing, and Canadian documents reviewed live</li></ul>",
        16:eng.IMPL,
        17:eng.COST_TABLE,
        18:"<p>Rs 10, including GST, refundable anytime. If the facts tell you Canada is not for you yet, that answer cost you Rs 10, and you can still ask for it back.</p>",
        19:"<p class='quote'>\"I do not need a Canadian degree. The NCA assesses my Indian LLB.\"</p><p>You are in the right room if you hold an Indian LLB, you want to practise law in Canada, and you prefer facts to forum advice.</p>",
        20:"<p>Press the button and pay Rs 10. Joining details come on WhatsApp and email. Keep your mark sheets handy for Day 1.</p>",
        21:"<p>Indian law graduates who want to practise in Canada usually stop at a myth. The bootcamp replaces it with the facts, and the route that follows.</p>"}),

dict(stem="nca_d_03_ticket_newly_enrolled", slug="nca-oct-d03-try-route", ac="#9E2328", soft="#F6E9E6",
     title="Try the Canada route before you commit to it",
     qual="NEWLY ENROLLED ADVOCATES · JUNIOR ASSOCIATES · RECENT LLB GRADUATES",
     h1="Newly enrolled advocate? <em>Try the Canada route before you commit to it.</em>",
     offer="Admit one, live, for Rs 10. In 3 days you write an NCA-style answer and leave with a 12-month plan built around about 2 hours a day after court. If it is not for you, ask for the Rs 10 back.",
     t={2:"Canada sounds big. Your first year already feels full",
        3:"What you want: to find out if it is for you, cheaply",
        4:"Failed alternative 1: deciding before you have tried",
        5:"Failed alternative 2: buying a course before you know the route",
        6:"Failed alternative 3: asking seniors who never took the route",
        7:"The problem is not commitment. It is information",
        8:"What not trying costs",
        9:"The offer: a 9-hour trial of the whole route",
        10:"What the route looks like, in 3 steps",
        11:"What you take away first: one exam answer, written by you",
        12:"Where a small start leads",
        13:"Proof: Canadian work while still preparing",
        14:"Proof: a job lined up before the move",
        15:"Exactly what you try in the 3 days",
        16:"The details",
        17:"What it costs to try, compared",
        18:"The risk: none you cannot take back",
        19:"How to explain it to your senior",
        20:"Your next step",
        21:"New advocates can try the route now, for Rs 10"},
     s={1:"This page is for advocates in their first years of practice who are curious about Canada but not ready to commit to anything yet.",
        2:"<p>You are learning court, drafting for a senior and earning very little. Canada keeps coming up, from friends abroad and from posts you scroll past at night. But it sounds like a decision with a lot of zeros in it.</p><p>So you do what most juniors do. You save the posts, you tell yourself you will look at it properly one day, and the day does not come.</p>",
        3:"<p>You want to find out whether the Canada route is right for you before you spend real money or time on it.</p>",
        4:"<p>Some juniors decide 'not for me' without ever seeing the route. Others decide 'yes' on a friend's word. Both are guesses. Three evenings of trying the real thing turns the guess into an answer.</p><p>Trying first is how sensible people make big decisions everywhere else. You sit one class before joining a course. You read a sample before buying a book. Canada deserves the same.</p>",
        5:"<p>Paying for a full prep course or a foreign degree first is the expensive way to learn whether you even like the material. Try it before you buy anything large.</p><p>The trial costs Rs 10 and comes back if you ask. A wrong guess the other way can cost lakhs and a year.</p>",
        6:"<p>Seniors give good advice about Indian practice. Very few of them have taken the NCA route, so on Canada their advice is a guess too.</p><p>The people who can tell you what the route is really like are those who have walked it, and the bootcamp brings that experience into one room for three days.</p>",
        7:"<p>You do not lack commitment. You lack information, and information is cheap to get. Once you have it, your position changes: from a junior wondering about Canada to a junior with a tested plan.</p><p>Tested matters. A plan you have tried for three days, with an answer you wrote yourself, is one you will actually follow.</p>",
        8:"<p>Not trying costs you the easiest years to start. Early evenings are the most flexible you will have, and the route rewards steady preparation started early.</p><p>It also costs you the comparison. Without trying, you cannot tell whether your real interest is Canada, another country or staying in India. The trial answers that too.</p>",
        9:"<p>A 3-day live bootcamp, 9 hours in all, that lets you try every stage of the route. Rs 10, refundable, timed around court.</p>"
          + eng.why("What you would be trying for:"),
        10:"<ol class='steps'><li><b>NCA exams, from India.</b> About 2 hours a day on the core subjects, in our bootcamp's plan, written online from home.</li><li><b>Small Canadian work while you prepare.</b> Research and drafting support for Canadian lawyers and startups, found on LinkedIn and Upwork.</li><li><b>Bar licensing, then practise in Canada.</b> With the Certificate of Qualification, you take your province's licensing step.</li></ol>",
        11:"<p>On Day 1 you write an NCA-style answer yourself, in the IRAC format. It is the fastest way to know whether this kind of exam suits you, before you pay a single NCA fee.</p>",
        12:"<p>If the trial says yes, you leave Day 2 with a 12-month plan and a weekly timetable around court. In a few years, you are not only more senior; you are on the route to a second country.</p>",
        13:"<p>Harshmir Swaitch worked as a legal assistant at a Canadian firm on NRI and immigration matters while preparing, as our bootcamp tells it. The Canadian work started from India.</p>",
        14:"<p>Yashika Malhotra, a litigator, had a Canadian job lined up before moving, in our bootcamp's own account. Small steps first, the big one last.</p><p>Neither story started with a big commitment. Both started with information and a plan, which is exactly what the trial gives you.</p>",
        15:"<ul class='del'><li>Day 1: how the NCA works for an Indian LLB, and your own IRAC answer</li><li>Day 2: the 12-month plan, your weekly timetable, and finding Canadian work online</li><li>Day 3: Canadian documents reviewed live, and the bar licensing step</li></ul>",
        16:eng.IMPL,
        17:eng.COST_TABLE,
        18:"<p>Rs 10, including GST. If it is not for you, ask for the Rs 10 back, any time. You keep the answer you wrote and the plan you built.</p>",
        19:"<p class='quote'>\"I am trying the Canada route for three days before I decide anything.\"</p><p>You are in the right room if you are early in your career, curious about Canada, and want to try before you commit.</p>",
        20:"<p>Press the button and pay Rs 10. Your joining link comes on WhatsApp and email. Block the three slots; there are no recordings.</p>",
        21:"<p>Newly enrolled advocates do not have to decide about Canada today. For Rs 10 and three sessions, you can try the whole route first.</p>"}),

dict(stem="nca_d_04_split_contract_lawyers", slug="nca-oct-d04-same-drafting", ac="#0E5A6C", soft="#E3EEF2",
     title="Same drafting. Dual-qualify in two countries",
     qual="CORPORATE LAWYERS · CONTRACT DRAFTERS · M&A · IN-HOUSE COUNSEL",
     h1="Corporate or contract lawyer? <em>Same drafting. Dual-qualify in two countries.</em>",
     offer="The shareholders' agreements, service contracts, NDAs and privacy policies you draft now are the documents Canadian clients need too. In 3 live days, we show you how to qualify to draft them for Canada.",
     t={2:"Your documents are good enough for any market. Your licence is not",
        3:"What you want: to draft the same documents for Canadian clients",
        4:"Failed alternative 1: drafting for foreign clients without a licence",
        5:"Failed alternative 2: waiting for a cross-border deal to come to you",
        6:"Failed alternative 3: a general LLM in 'international law'",
        7:"The problem is not your drafting. It is your position",
        8:"What a one-country licence costs a drafter",
        9:"The offer: try the dual-qualify route for Rs 10",
        10:"The route, in 3 steps",
        11:"What you take away first: one clause, read the Canadian way",
        12:"What a dual-qualified drafter's work looks like",
        13:"Proof: drafting for clients in three countries, from Ludhiana",
        14:"Proof: in-house, Mumbai to Vancouver",
        15:"Document by document: India today, Canada next",
        16:"The details",
        17:"The cost of each route",
        18:"The risk",
        19:"How to say it to a partner or your GC",
        20:"Your next step",
        21:"Corporate lawyers already draft the documents. This qualifies you to draft them for Canada"},
     s={1:"This page is for lawyers who draft, review or negotiate contracts for a living, at a firm, in-house or in their own practice.",
        2:"<p>A shareholders' agreement you draft in Mumbai would read well in Toronto. The structure, the protections, the boilerplate: you know it all. What you cannot do is advise on it under Canadian law, because your licence stops at the border.</p><p>So the Canadian side of a deal gets drafted by someone else, even when your clients would rather keep it with you.</p>",
        3:"<p>You want to draft the same documents for Canadian clients, as a lawyer qualified to advise them.</p>",
        4:"<p>Some drafters sell contract work abroad on platforms without a local qualification. Serious clients notice, and you end up competing on price with every unqualified drafter online.</p>",
        5:"<p>Cross-border mandates go to the few lawyers already qualified on both sides. Waiting for one to arrive leaves your position exactly where it is.</p>",
        6:"<p>A general LLM in international law sounds relevant, costs lakhs and still does not license you to practise in Canada. A Canadian licence comes through the NCA route.</p><p>For a drafter with clients and a track record, a year abroad also means handing those clients to someone else while you study.</p>",
        7:"<p>Your drafting is not the gap. Canada, like India, is a common-law country. The gap is position: you are seen as an Indian-law drafter. Dual qualification makes you a drafter Canadian clients can instruct directly.</p><p>Some rules do differ, and they are exactly what the NCA exams test: how Canadian courts read restraint clauses, consumer protections and privacy duties. The bootcamp shows you where.</p>",
        8:"<p>A one-country licence caps who can hire you for the documents you already draft well. The skill keeps growing; the market it is allowed into stays the same size.</p><p>It also caps the matters you see. The more interesting cross-border work goes to whoever is qualified on the Canadian side.</p>",
        9:"<p>A 3-day live bootcamp with Canadian documents reviewed live. Try the route for Rs 10, refundable.</p>"
          + eng.why("Why Canada suits a drafter:"),
        10:"<ol class='steps'><li><b>NCA exams from India.</b> The NCA assesses your LLB and sets the subjects. You write them online alongside your work.</li><li><b>Canadian contract work while you prepare.</b> Contracts valid in Canada, startup privacy policies and incorporation support, found on LinkedIn, Upwork and law-society directories.</li><li><b>Bar licensing.</b> With the Certificate of Qualification you take your province's licensing step, then advise Canadian clients as a qualified lawyer.</li></ol>",
        11:"<p>On Day 3 you review a non-compete clause under Canadian law, live. You see which of your instincts carry over and where Canadian courts read the clause differently, and you keep your marked-up copy.</p>",
        12:"<p>Your client list stops at no border. Indian companies entering Canada, Canadian startups and businesses with work in both countries can all instruct you directly.</p><p>Inside a firm or legal team, you become the person who can take the Canadian side of a deal. In your own practice, you offer Canadian clients the same careful drafting you already offer Indian ones.</p><div class='box'><p><b>Market data, not a promise:</b> Canada's Job Bank reports a median wage of CAD 65.21 an hour for lawyers in Ontario, with a moderate outlook for 2025 to 2027.</p><p class='src'>Source: jobbank.gc.ca, NOC 41101, Ontario.</p></div>",
        13:"<p>Shashwat Jindal practises from Ludhiana. In our bootcamp's own account, the practice took on work for four US firms, a Canadian firm and five startups, all from India.</p>",
        14:"<p>Hezal Shah was an in-house lawyer in Mumbai and, as our bootcamp tells it, moved to Vancouver after qualifying first.</p>",
        15:"<table><tr><th>Document</th><th>India, today</th><th>Canada, next (seen in the bootcamp)</th></tr><tr><td>Employment agreement</td><td>You draft it under Indian law</td><td>A Canadian employment agreement, reviewed on Day 2</td></tr><tr><td>Non-compete</td><td>You negotiate it</td><td>Reviewed under Canadian law on Day 3</td></tr><tr><td>Company set-up</td><td>Indian incorporation</td><td>Incorporating a Canadian company, Day 3</td></tr><tr><td>Privacy policy</td><td>Indian clients' policies</td><td>A privacy policy for a Canadian founder, Day 3</td></tr><tr><td>Client questions</td><td>Indian expansion queries</td><td>The top 20 questions a CEO asks before expanding into Canada, Day 3</td></tr></table>",
        16:eng.IMPL,
        17:eng.COST_TABLE,
        18:"<p>Rs 10, including GST, refundable anytime. You keep every document you mark up during the sessions.</p><p>The sessions sit on a Saturday and Sunday afternoon and a Monday evening, so they do not collide with a week of closings and calls.</p>",
        19:"<p class='quote'>\"I am qualifying in Canada so I can draft the same documents for Canadian clients.\"</p><p>You are in the right room if contracts are your daily work and you want them to cross a border with you.</p>",
        20:"<p>Press the button and pay Rs 10. The joining link comes on WhatsApp and email. Bring a contract you drafted recently.</p><p>By Day 3 you will read it the way a Canadian client's lawyer would, and you will know which clauses travel and which need work.</p>",
        21:"<p>Corporate and contract lawyers already draft documents Canadian clients need. The bootcamp shows you the route to be qualified to draft them for Canada.</p>"}),
]

if __name__ == "__main__":
    os.makedirs(OUT, exist_ok=True)
    for p in PAGES:
        assert sorted(p["s"]) == list(range(1, 22)) and sorted(p["t"]) == list(range(2, 22)), p["stem"]
        html = eng.page(p).replace("Join the Rs 10 bootcamp", CTA_AD)
        with open(os.path.join(OUT, "lp_%s.html" % p["stem"]), "w") as f:
            f.write(html)
        print("lp_%s.html" % p["stem"])
